### ISSUE TITLE
How to configure directly, via config file

### ISSUE THREAD

**Issue by vgoklani** [rahiel/telegram-send#34]
Hi - is there a way to configure the tool to read the api-key from a config file. so we don't have to use the interactive bot: 
```
telegram-send --configure
```

I would like to set this up in a Docker container, that runs remotely, and pushes messages from supervisord

**Comment by rahiel** [comment]
You can write the config file once to a known location on your (non-container) computer:
``` shell
telegram-send --configure --config ~/telegram-send.conf
```
Then copy that file to a known location in the container, I recommend `/etc/telegram-send.conf`. Then within the container you use `telegram-send --config /etc/telegram-send.conf` and whatever options/messages you'd like to send. I recommend this particular config location because you can then use `telegram-send -g` within the container, because the `-g` options defaults the config location to `/etc/telegram-send.conf`.

**Comment by ideniska** [comment]
@rahiel thanks for the answer, I am quite new to Docker, could you please elaborate how to use "telegram-send --config /etc/telegram-send.conf" within the container ?
