### ISSUE TITLE
How to configure telegram-send?

### ISSUE THREAD

**Issue by jk-1** [rahiel/telegram-send#40]
I installed telegram-send into Ubuntu 16.04 box.

When I run telegram-send --configure I get:

	jk@ka:~$ telegram-send --configure
	Talk with the BotFather on Telegram (https://telegram.me/BotFather), create a bot and insert the token
	❯ /newbot
	Something went wrong, please try again.
	
	Traceback (most recent call last):
	  File "/home/jk/.local/lib/python3.5/site-packages/telegram_send.py", line 254, in configure
	    bot = telegram.Bot(token)
	  File "/home/jk/.local/lib/python3.5/site-packages/telegram/bot.py", line 108, in __init__
	    self.token = self._validate_token(token)
	  File "/home/jk/.local/lib/python3.5/site-packages/telegram/bot.py", line 134, in _validate_token
	    raise InvalidToken()
	telegram.error.InvalidToken: Invalid token
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/home/jk/.local/bin/telegram-send", line 11, in <module>
	    sys.exit(main())
	  File "/home/jk/.local/lib/python3.5/site-packages/telegram_send.py", line 79, in main
	    return configure(conf, fm_integration=True)
	  File "/home/jk/.local/lib/python3.5/site-packages/telegram_send.py", line 258, in configure
	    return configure()
	TypeError: configure() missing 1 required positional argument: 'conf'
	

All configure options --configure --configure-group  --configure-channel start "Talk with the BotFather" to create bot which then fails.

1) How to fix this?

2) How can I create/edit manually conf files? Where can I find examples of conf files or links to conf file specs?

Thank you for your support.

**Comment by rahiel** [comment]
At that prompt you have to insert the token you get from the BotFather. You have to talk with that bot on Telegram (by going to https://telegram.me/BotFather and starting a chat), requesting a bot, and then you paste in the token you get at the prompt. The "/newbot" command is what you send to the BotFather, not to telegram-send.

**Comment by rahiel** [comment]
> How can I create/edit manually conf files? Where can I find examples of conf files or links to conf file specs?

Here is an example `telegram-send.conf`:
``` ini
[telegram]
token = 123456:FsadfsdafWGsDFbvFDSKAEfldsafKGFAG
chat_id = 123456789
```
Where `token` is the bot's token, and `chat_id` your account id within the Telegram network.

**Comment by rahiel** [comment]
@davincino You can specify the config location with `--config`, so if it's at `~/telegram-send.conf`, pass in `--config ~/telegram-send.conf`.

You can also put the config at `/etc/telegram-send.conf`, then you always need to pass the `-g` option, so then you use `telegram-send -g "hello world"`.

**Comment by davincino** [comment]
Ah ok. With the option -g it works. Thank you.

**Comment by rahiel** [comment]
I assume your question was answered, please open a new issue if you need further help with telegram-send.

**Comment by edoardoga** [comment]
Hi! I'm facing an issue of the same kind of what discussed above. 
Let me explain... I have a piece of python code that I would like to run once per day and that would be able to send me a message on telegram every time is executed. For this reason I'm using Deepnote with the api connection to a telegram bot I created. 

Now, the problem is that if inside the code I put only 
`!telegram-send --config`
botfather asks me for the api every time !
So it's clear that a telegram-send.conf file is needed (the aim is create a code fully automated)

But , after setting the conf file using your example above the problem comes out on 
`telegram_send.send(messages=["bla bla bla!"])`
saying "ConfigError: Config not found"
<img width="886" alt="Schermata 2022-09-13 alle 13 50 36" src="https://user-images.githubusercontent.com/100435498/189893701-9e3f4d9b-052b-46d5-aa02-b6fcf5e12355.png">

So, my question is :
Why if `!telegram-send --configure ~/work/telegram-send.conf` works, `telegram_send.send(messages=["bla bla bla!"])` this doesn't ? 

Thank you

**Comment by rahiel** [comment]
> So, my question is :
> Why if `!telegram-send --configure ~/work/telegram-send.conf` works, `telegram_send.send(messages=["bla bla bla!"])` this doesn't ?

@edoardoga If you've set it up with 
`telegram-send --configure ~/work/telegram-send.conf`

then you also send messages with
`telegram_send.send(messages=["bla bla bla!"], conf="~/work/telegram-send.conf")`
